# Sieu tham so cho mo hinh RandomForestClassifier
# Thay doi cac gia tri nay giua cac lan chay de thi nghiem (Buoc 1)
train:
  model_type: "random_forest"
  n_estimators: 1000
  max_depth: 30
  min_samples_split: 2
